#!/bin/sh

if ! grid-proxy-info -exists -valid 1:0 2>/dev/null; then
  read -p "Enter your LIGO.ORG username: " username && echo $username | xargs -n 1 ligo-proxy-init
fi

sudo sh -c 'mount -a 2>&1 >/dev/null'
exec "$@"
